spring:
  redis:
    host: redis-server
    port: 6379
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-server:9411

server:
  port: 80

jwt:
  secret: my-secret

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/


zuul:
#  ignored-services: "*"
  routes:
    authentication-service:
      path: /auth/**
      serviceId: authentication-service
    member-service:
      path: /api/member/**
      serviceId: member-service
    order-service:
      path: /api/order/**
      serviceId: order-service
    product-service:
      path: /api/product/**
      serviceId: product-service
  sensitive-headers:


management:
  endpoints:
    web:
      exposure:
        include: routes

logging:
  level:
    org.springframework: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000

