spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: "jdbc:h2:~/e-commerce-dev;AUTO_SERVER=TRUE"
  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

jwt:
  secret: my-secret
server:
  port: 8082

logging:
  level:
    org.springframework: DEBUG