spring:
  redis:
    host: redis-server
    port: 6379

  datasource:
    url: jdbc:mysql://db:3306/e-commerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer!23

  jpa:
    database: mysql
    show-sql: on
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-server:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: my-secret

logging:
  level:
    org.springframework: DEBUG