spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false
      discovery:
        enabled: false
  redis:
    host: localhost
    port: 6379

  jpa:
    show-sql: on
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:~/e-commerce

jwt:
  secret: my-secret
server:
  port: 8082
