version: '2'
services:
  redis-server:
    image: redis
    ports:
      - "6379:6379"
  eureka-server:
    image: sup2is/e-commerce-eureka-server:0.1
    ports:
      - "8761:8761"
  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwer!23"
      MYSQL_DATABASE: "e-commerce"
    ports:
      - "3306:3306"

  documents:
    image: nginx
    environment:
     - NGINX_PORT=80
    ports:
      - "8000:80"
    volumes:
      - "../docs/:/usr/share/nginx/html"
    privileged: true 

  api-gateway:
    image: sup2is/e-commerce-api-gateway:0.1
    ports:
      - "8080-8082:8080"
    environment:
      REDIS_SERVER_PORT: 6379
      EUREKA_SERVER_PORT: 8761
      ZIPKIN_SERVER_PORT: 9411
      DATASOURCE_PORT: 3306
      SERVER_PORT: 8080
      PROFILE: dev-integration
    depends_on:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"
    links:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"

  auth-service:
    image: sup2is/e-commerce-auth-service:0.1
    environment:
      REDIS_SERVER_PORT: 6379
      EUREKA_SERVER_PORT: 8761
      ZIPKIN_SERVER_PORT: 9411
      DATASOURCE_PORT: 3306
      SERVER_PORT: 0
      PROFILE: dev-integration
    depends_on:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"
    links:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"

  member-service:
    image: sup2is/e-commerce-member-service:0.1
    environment:
      REDIS_SERVER_PORT: 6379
      EUREKA_SERVER_PORT: 8761
      ZIPKIN_SERVER_PORT: 9411
      DATASOURCE_PORT: 3306
      SERVER_PORT: 0
      PROFILE: dev-integration
    depends_on:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"
    links:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"


  product-service:
    image: sup2is/e-commerce-product-service:0.1
    environment:
      REDIS_SERVER_PORT: 6379
      EUREKA_SERVER_PORT: 8761
      ZIPKIN_SERVER_PORT: 9411
      DATASOURCE_PORT: 3306
      SERVER_PORT: 0
      PROFILE: dev-integration
    depends_on:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"
    links:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"

  order-service:
    image: sup2is/e-commerce-order-service:0.1
    environment:
      REDIS_SERVER_PORT: 6379
      EUREKA_SERVER_PORT: 8761
      ZIPKIN_SERVER_PORT: 9411
      DATASOURCE_PORT: 3306
      SERVER_PORT: 0
      PROFILE: dev-integration
    depends_on:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"
    links:
      - "redis-server"
      - "eureka-server"
      - "zipkin-server"
      - "db"
