spring:
  redis:
    host: redis-server
    port: 6379
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://zipkin-server:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://zipkin-server:9411

jwt:
  secret: my-secret


logging:
  level:
    org.springframework: DEBUG