spring:
  cloud:
    discovery:
      enabled: false

  jpa:
    show-sql: on
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:h2:~/e-commerce-local

jwt:
  secret: my-secret
server:
  port: 8084
