spring:
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

datasource:
  url: jdbc:h2:~/e-commerce-dev

jwt:
  secret: my-secret
server:
  port: 8083