spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serverUrl:
    defaultZone: http://127.0.0.1:8671
  instance:
    status-page-url: 127.0.0.1/info
    health-check-url: 127.0.0.1/health

jwt:
  secret: my-secret
