spring:
  redis:
    host: 192.168.0.11
    port: 6379

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serverUrl:
    defaultZone: http://127.0.0.1:8671

jwt:
  secret: my-secret
